# Generated by Django 4.2.26 on 2025-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('specialties', models.CharField(blank=True, help_text='Comma-separated specialties', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('haircuts', 'Haircuts'), ('beards', 'Beards'), ('fades', 'Fades'), ('styles', 'Styles'), ('shop', 'Shop')], default='haircuts', max_length=50)),
                ('alt_text', models.CharField(blank=True, help_text='Image alt text for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['category', 'order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(blank=True, help_text='e.g., Haircuts, Beard, Combo', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Barber Shop', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps iframe embed code')),
                ('fresha_url', models.URLField(blank=True, help_text='Fresha booking URL')),
                ('fresha_shop_id', models.CharField(blank=True, help_text='Fresha shop ID for widget', max_length=50)),
                ('opening_hours', models.TextField(blank=True, default='{"monday": "9:00 - 19:00", "tuesday": "9:00 - 19:00", "wednesday": "9:00 - 19:00", "thursday": "9:00 - 19:00", "friday": "9:00 - 19:00", "saturday": "9:00 - 17:00", "sunday": "Closed"}', help_text='JSON format opening hours')),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('hero_title', models.CharField(default='Premium Grooming Experience', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Expert cuts, classic shaves, and modern styles.')),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Shop Information',
                'verbose_name_plural': 'Shop Information',
            },
        ),
    ]
